using UnityEngine;
using System.Collections;

/// <summary>
/// 控制玩家按下 Q 鍵發動護盾的機制：
/// 1. 自動在玩家座標 Y + 2 的位置啟用/跟隨護盾。
/// 2. 包含護盾持續時間 (Duration) 與技能冷卻時間 (Cooldown)。
/// 3. 若 Inspector 上的 shieldObject 留空，自動幫玩家生成一個具備碰撞與發光質感的預設護盾。
/// 4. 支援抵擋飛鳥與敵人的衝撞。
/// </summary>
public class PlayerShield : MonoBehaviour, IResettable
{
    [Header("按鍵與時間設定")]
    [Tooltip("發動護盾的按鍵 (預設 Q)")]
    public KeyCode shieldKey = KeyCode.Q;

    [Tooltip("護盾持續時間 (秒，預設 3)")]
    public float shieldDuration = 3.0f;

    [Tooltip("技能冷卻時間 (秒，預設 5)")]
    public float cooldownDuration = 5.0f;

    [Header("位置與物理設定")]
    [Tooltip("護盾相對於玩家座標的偏移量 (預設 Y + 2)")]
    public Vector3 offsetFromPlayer = new Vector3(0f, 2.0f, 0f);

    [Tooltip("擊退敵人的力量 (建議 15~20)")]
    public float knockbackForce = 15f;

    [Header("視覺物件")]
    [Tooltip("護盾 GameObject (若留空，系統會自動在 Y+2 生成一個帶發光視覺與碰撞的護盾)")]
    public GameObject shieldObject;

    // 狀態追蹤
    public bool IsShieldActive => shieldObject != null && shieldObject.activeSelf;
    public float CurrentCooldownTimer => cooldownTimer;
    public bool IsReady => cooldownTimer <= 0f && !IsShieldActive;

    private float cooldownTimer = 0f;
    private Coroutine shieldCoroutine;
    private PlayerPetrification petrification;

    private void Start()
    {
        petrification = GetComponent<PlayerPetrification>();
        if (petrification == null) petrification = GetComponentInChildren<PlayerPetrification>();

        EnsureShieldObject();

        if (shieldObject != null)
        {
            shieldObject.SetActive(false);
        }
    }

    /// <summary>
    /// 防呆備用機制：若用戶未在 Inspector 手動拉入 shieldObject，
    /// 自動建立一個位於 Y+2 的發光球體 Trigger Collider 當作護盾。
    /// </summary>
    private void EnsureShieldObject()
    {
        if (shieldObject != null)
        {
            // 確保有位置偏移
            shieldObject.transform.localPosition = offsetFromPlayer;
            EnsureShieldCollider(shieldObject);
            return;
        }

        // 搜尋子物件中名為 Shield 的物件
        Transform childShield = transform.Find("Shield");
        if (childShield != null)
        {
            shieldObject = childShield.gameObject;
            shieldObject.transform.localPosition = offsetFromPlayer;
            EnsureShieldCollider(shieldObject);
            return;
        }

        // 自動生成備用 3D 發光護盾球體
        GameObject newShield = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        newShield.name = "PlayerShield_AutoGenerated";
        newShield.transform.SetParent(this.transform, false);
        newShield.transform.localPosition = offsetFromPlayer;
        newShield.transform.localScale = new Vector3(3.0f, 3.0f, 3.0f); // 護盾直徑 3 米

        // 設定 Trigger Collider
        SphereCollider col = newShield.GetComponent<SphereCollider>();
        if (col != null)
        {
            col.isTrigger = true;
        }

        // 設定半透明藍/半透明白發光材質
        Renderer r = newShield.GetComponent<Renderer>();
        if (r != null)
        {
            Material shieldMat = new Material(Shader.Find("Sprites/Default"));
            shieldMat.color = new Color(0.3f, 0.7f, 1.0f, 0.4f); // 柔和半透明水藍色
            r.material = shieldMat;
        }

        shieldObject = newShield;
        Debug.Log("[PlayerShield] 已自動在 Y+2 位置生成備用發光護盾！");
    }

    private void EnsureShieldCollider(GameObject obj)
    {
        Collider col = obj.GetComponent<Collider>();
        if (col == null) col = obj.GetComponentInChildren<Collider>();
        if (col != null)
        {
            col.isTrigger = true;
        }
    }

    private void Update()
    {
        // 更新技能冷卻時間
        if (cooldownTimer > 0f)
        {
            cooldownTimer -= Time.deltaTime;
        }

        // 按鍵發動判定
        if (Input.GetKeyDown(shieldKey) || Input.GetKeyDown(KeyCode.Q))
        {
            // 若處於石化中，不可開護盾
            if (petrification != null && petrification.isPetrified)
            {
                Debug.Log("【護盾系統】玩家石化中，無法發動護盾！");
                return;
            }

            if (cooldownTimer > 0f)
            {
                Debug.Log($"【護盾系統】護盾冷卻中... 還需等待 {cooldownTimer:F1} 秒！");
                return;
            }

            ActivateShield();
        }

        // 若護盾開啟中且非子物件，持續保持跟隨玩家 Y+2 的座標
        if (IsShieldActive && shieldObject != null && shieldObject.transform.parent != this.transform)
        {
            shieldObject.transform.position = transform.position + offsetFromPlayer;
        }
    }

    public void ActivateShield()
    {
        EnsureShieldObject();
        if (shieldObject == null) return;

        if (shieldCoroutine != null)
        {
            StopCoroutine(shieldCoroutine);
        }
        shieldCoroutine = StartCoroutine(ShieldActiveCoroutine());
    }

    private IEnumerator ShieldActiveCoroutine()
    {
        // 校正 Y+2 位置
        if (shieldObject.transform.parent == this.transform)
        {
            shieldObject.transform.localPosition = offsetFromPlayer;
        }
        else
        {
            shieldObject.transform.position = transform.position + offsetFromPlayer;
        }

        shieldObject.SetActive(true);
        Debug.Log("【護盾系統】按下 Q 鍵！護盾成功發動（位置：Y+2）！");

        // 等待護盾持續時間
        yield return new WaitForSeconds(shieldDuration);

        // 關閉護盾並啟動冷卻
        shieldObject.SetActive(false);
        cooldownTimer = cooldownDuration;
        shieldCoroutine = null;
        Debug.Log($"【護盾系統】護盾持續時間結束，進入 {cooldownDuration} 秒技能冷卻。");
    }

    // --- IResettable 實作 ---
    public void ResetToInitialState()
    {
        if (shieldCoroutine != null)
        {
            StopCoroutine(shieldCoroutine);
            shieldCoroutine = null;
        }
        cooldownTimer = 0f;
        if (shieldObject != null)
        {
            shieldObject.SetActive(false);
        }
    }
}
