using UnityEngine;
using System.Collections;

/// <summary>
/// 控制玩家按下 Q 鍵發動護盾的機制：
/// 1. 不管腳本掛在 Player 根物件還是子物件 (如 Shield/Generated_3D_Collider)，都能自動鎖定 Player 根物件。
/// 2. 啟動時精確對齊玩家 Y + 2 的位置，且不會無限累加飛走。
/// 3. 自動將護盾上的所有 Collider 設為 isTrigger = true，防止物理實體碰撞導致玩家卡死。
/// 4. 包含 3 秒持續時間與 5 秒技能冷卻機制。
/// </summary>
public class PlayerShield : MonoBehaviour, IResettable
{
    [Header("按鍵與時間設定")]
    [Tooltip("發動護盾的按鍵 (預設 Q)")]
    public KeyCode shieldKey = KeyCode.Q;

    [Tooltip("護盾持續時間 (秒，預設 3)")]
    public float shieldDuration = 3.0f;

    [Tooltip("技能冷卻時間 (秒，預設 5)")]
    public float cooldownDuration = 5.0f;

    [Header("位置與物理設定")]
    [Tooltip("護盾相對於玩家座標的偏移量 (預設 Y + 2)")]
    public Vector3 offsetFromPlayer = new Vector3(0f, 2.0f, 0f);

    [Tooltip("擊退敵人的力量 (建議 15~20)")]
    public float knockbackForce = 15f;

    [Header("視覺物件")]
    [Tooltip("護盾 GameObject (請拖入名為 Shield 的子物件)")]
    public GameObject shieldObject;

    // 狀態追蹤
    public bool IsShieldActive => shieldObject != null && shieldObject.activeSelf;
    public float CurrentCooldownTimer => cooldownTimer;
    public bool IsReady => cooldownTimer <= 0f && !IsShieldActive;

    private float cooldownTimer = 0f;
    private Coroutine shieldCoroutine;
    private PlayerPetrification petrification;
    private Transform playerRoot; // 自動鎖定 Player 根物件

    private void Start()
    {
        LocatePlayerRoot();
        EnsureShieldObject();

        if (shieldObject != null)
        {
            shieldObject.SetActive(false);
        }
    }

    /// <summary>
    /// 自動尋找 Player 根物件，解決腳本誤掛在子物件時定位錯誤的問題
    /// </summary>
    private void LocatePlayerRoot()
    {
        if (transform.CompareTag("Player") || transform.name == "Player")
        {
            playerRoot = transform;
        }
        else
        {
            // 如果腳本被誤掛在 Shield 或 Generated_3D_Collider 等子物件上，自動找最頂層 Player
            playerRoot = transform.root;
            Debug.LogWarning($"[PlayerShield] 偵測到腳本掛在子物件 '{gameObject.name}' 上，已自動定位玩家根物件為 '{playerRoot.name}'！");
        }

        petrification = playerRoot.GetComponent<PlayerPetrification>();
        if (petrification == null) petrification = playerRoot.GetComponentInChildren<PlayerPetrification>();
    }

    /// <summary>
    /// 自動尋找並校正護盾物件與 Trigger Collider，防止實體碰撞卡死
    /// </summary>
    private void EnsureShieldObject()
    {
        if (playerRoot == null) LocatePlayerRoot();

        // 1. 若手動拖入了 shieldObject
        if (shieldObject != null)
        {
            EnsureShieldCollider(shieldObject);
            EnsureShieldMaterial(shieldObject);
            return;
        }

        // 2. 搜尋子物件中名為 Shield 或包含 Shield 的物件
        Transform childShield = playerRoot.Find("Shield");
        if (childShield == null) childShield = transform.Find("Shield");
        if (childShield != null)
        {
            shieldObject = childShield.gameObject;
            EnsureShieldCollider(shieldObject);
            EnsureShieldMaterial(shieldObject);
            return;
        }

        // 3. 備用方案：自動生成一個發光護盾球體
        GameObject newShield = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        newShield.name = "PlayerShield_AutoGenerated";
        newShield.transform.SetParent(playerRoot, false);
        newShield.transform.localPosition = offsetFromPlayer;
        newShield.transform.localScale = new Vector3(3.0f, 3.0f, 3.0f);

        SphereCollider col = newShield.GetComponent<SphereCollider>();
        if (col != null) col.isTrigger = true;

        EnsureShieldMaterial(newShield);

        shieldObject = newShield;
    }

    /// <summary>
    /// 自動賦予相容 URP / Built-in 管線的水藍色發光護盾材質
    /// </summary>
    private void EnsureShieldMaterial(GameObject obj)
    {
        Renderer r = obj.GetComponent<Renderer>();
        if (r == null) r = obj.GetComponentInChildren<Renderer>();
        if (r == null) return;

        // 如果已經有合法材質則跳過
        if (r.sharedMaterial != null && r.sharedMaterial.name != "Default-Material")
        {
            return;
        }

        // 嘗試多種 Shader 備用方案 (相容 URP 與 Standard)
        Shader shader = Shader.Find("Universal Render Pipeline/Unlit");
        if (shader == null) shader = Shader.Find("Universal Render Pipeline/Lit");
        if (shader == null) shader = Shader.Find("Sprites/Default");
        if (shader == null) shader = Shader.Find("Unlit/Color");
        if (shader == null) shader = Shader.Find("Standard");

        Material shieldMat = new Material(shader != null ? shader : Shader.Find("Sprites/Default"));
        Color shieldColor = new Color(0.2f, 0.75f, 1.0f, 0.45f);

        if (shieldMat.HasProperty("_BaseColor"))
        {
            shieldMat.SetColor("_BaseColor", shieldColor);
        }
        if (shieldMat.HasProperty("_Color"))
        {
            shieldMat.color = shieldColor;
        }

        // 透明渲染設定
        shieldMat.SetFloat("_Surface", 1); // Transparent
        shieldMat.SetFloat("_Blend", 0);   // Alpha
        shieldMat.renderQueue = 3000;

        r.material = shieldMat;
    }

    /// <summary>
    /// 強制將護盾上的所有 Collider 設為 isTrigger = true！
    /// 這是防止玩家與護盾產生實體物理摩擦進而卡死在原地的關鍵！
    /// </summary>
    private void EnsureShieldCollider(GameObject obj)
    {
        Collider[] colliders = obj.GetComponentsInChildren<Collider>(true);
        foreach (var col in colliders)
        {
            col.isTrigger = true; // 強制改為 Trigger，絕不允許 Solid Physics 摩擦卡死
        }
    }

    private void Update()
    {
        // 技能冷卻倒數
        if (cooldownTimer > 0f)
        {
            cooldownTimer -= Time.deltaTime;
        }

        // 按 Q 發動
        if (Input.GetKeyDown(shieldKey) || Input.GetKeyDown(KeyCode.Q))
        {
            if (petrification != null && petrification.isPetrified)
            {
                Debug.Log("【護盾系統】玩家石化中，無法發動護盾！");
                return;
            }

            if (cooldownTimer > 0f)
            {
                Debug.Log($"【護盾系統】護盾冷卻中... 還需等待 {cooldownTimer:F1} 秒！");
                return;
            }

            ActivateShield();
        }
    }

    public void ActivateShield()
    {
        if (playerRoot == null) LocatePlayerRoot();
        EnsureShieldObject();
        if (shieldObject == null) return;

        if (shieldCoroutine != null)
        {
            StopCoroutine(shieldCoroutine);
        }
        shieldCoroutine = StartCoroutine(ShieldActiveCoroutine());
    }

    /// <summary>
    /// 遞迴啟用/停用護盾及其所有子物件 (包含渲染器與碰撞器)，確保視覺貼圖不會因子物件關閉而隱形。
    /// </summary>
    private void EnableShieldHierarchy(GameObject obj, bool active)
    {
        if (obj == null) return;

        // 1. 遞迴開啟/關閉所有子 GameObject
        obj.SetActive(active);
        Transform[] allChildren = obj.GetComponentsInChildren<Transform>(true);
        foreach (var t in allChildren)
        {
            if (t != null && t.gameObject != null)
            {
                t.gameObject.SetActive(active);
            }
        }

        if (active)
        {
            // 2. 強制開啟所有 Renderer (MeshRenderer, SpriteRenderer 等)
            Renderer[] renderers = obj.GetComponentsInChildren<Renderer>(true);
            foreach (var r in renderers)
            {
                if (r != null) r.enabled = true;
            }

            // 3. 強制將所有 Collider 設為 Trigger 且開啟
            Collider[] colliders = obj.GetComponentsInChildren<Collider>(true);
            foreach (var c in colliders)
            {
                if (c != null)
                {
                    c.enabled = true;
                    c.isTrigger = true;
                }
            }
        }
    }

    private IEnumerator ShieldActiveCoroutine()
    {
        // 確保碰撞器與材質正確
        EnsureShieldCollider(shieldObject);
        EnsureShieldMaterial(shieldObject);

        // 校正護盾相對座標至 Y+2
        if (shieldObject.transform.IsChildOf(playerRoot))
        {
            shieldObject.transform.localPosition = offsetFromPlayer;
        }
        else
        {
            shieldObject.transform.position = playerRoot.position + offsetFromPlayer;
        }

        // 遞迴強制啟用護盾及其所有子物件、渲染器與碰撞器
        EnableShieldHierarchy(shieldObject, true);

        Debug.LogWarning($"【護盾系統】按下 Q 鍵成功發動！護盾已亮起！\n" +
                        $" - 護盾物件名稱: {shieldObject.name}\n" +
                        $" - 護盾世界座標: {shieldObject.transform.position}\n" +
                        $" - 相對座標 localPosition: {shieldObject.transform.localPosition}");

        // 在護盾持續時間內持續進行擊退與敵打飛判定
        float elapsed = 0f;
        while (elapsed < shieldDuration)
        {
            elapsed += Time.deltaTime;
            KnockbackEnemies();
            yield return null;
        }

        EnableShieldHierarchy(shieldObject, false);
        cooldownTimer = cooldownDuration;
        shieldCoroutine = null;
        Debug.Log($"【護盾系統】護盾結束，進入 {cooldownDuration} 秒技能冷卻。");
    }

    /// <summary>
    /// 擊退範圍內的所有敵人
    /// </summary>
    private void KnockbackEnemies()
    {
        if (shieldObject == null) return;

        Vector3 center = shieldObject.transform.position;
        float radius = 3.0f;

        SphereCollider sc = shieldObject.GetComponent<SphereCollider>();
        if (sc != null)
        {
            radius = sc.radius * Mathf.Max(shieldObject.transform.lossyScale.x, shieldObject.transform.lossyScale.y, shieldObject.transform.lossyScale.z);
        }

        Collider[] hits = Physics.OverlapSphere(center, radius);
        foreach (var hit in hits)
        {
            if (hit == null || hit.transform.IsChildOf(playerRoot)) continue;

            // 鳥類敵人
            IndividualBirdEnemy bird = hit.GetComponent<IndividualBirdEnemy>();
            if (bird == null) bird = hit.GetComponentInParent<IndividualBirdEnemy>();
            if (bird != null)
            {
                bird.OnShieldHit(this);
            }

            // 一般物理敵人擊退
            Rigidbody enemyRb = hit.GetComponent<Rigidbody>();
            if (enemyRb != null && !enemyRb.isKinematic)
            {
                Vector3 knockDir = (hit.transform.position - center).normalized;
                knockDir.y = Mathf.Max(knockDir.y, 0.3f);
                enemyRb.AddForce(knockDir * knockbackForce, ForceMode.Impulse);
            }
        }
    }

    public void ResetToInitialState()
    {
        if (shieldCoroutine != null)
        {
            StopCoroutine(shieldCoroutine);
            shieldCoroutine = null;
        }
        cooldownTimer = 0f;
        if (shieldObject != null)
        {
            shieldObject.SetActive(false);
        }
    }
}
